Fixed loadout card css temporarily.
drg-tools/karl.gg pull request #134
Opened 2020-09-07 07:23 UTC by surmiran

2020-09-07 17:25 UTC, chaseconey requested changes

2020-09-07 17:25 UTC, chaseconey commented on resources/scss/_dashboard.scss
> -    .loadoutCardContainer {
This is used on the homepage. The styles are all wonky on the homepage without it.

<img width="1034" alt="Screenshot_9_7_20__12_24_PM" src="https://user-images.githubusercontent.com/1449463/92409103-194f9d80-f105-11ea-98db-8146b13d748c.png">

2020-09-07 17:25 UTC, chaseconey commented on resources/scss/_dashboard.scss
> -    .titleRow {
Same with these as well.

2020-09-10 19:38 UTC, chaseconey commented
Deployed this to staging.

2020-09-11 07:58 UTC, surmiran commented
put aside until we know what and how to display on the front page

2020-09-11 07:58 UTC, closed without merging